### ISSUE TITLE
Wrong paper title

### ISSUE THREAD

**Issue by marcellacornia** [jonahthelion/cvpr_with_code#1]
Hi @jonahthelion, 
thanks for sharing these statistics.

This issue is just to inform you that our paper (ID 2710) is listed with a wrong title (_i.e._ the words "Controllable" and "Grounded" are switched), thus making impossible to find the source code from https://paperswithcode.com/. 

The correct title is: "Show, Control and Tell: A Framework for Generating Controllable and Grounded Captions", as reported in the CVPR website.
**Source code:** https://github.com/aimagelab/show-control-and-tell
**Paperwithcode link:** https://paperswithcode.com/paper/show-control-and-tell-a-framework-for

We would appreciate very much if you could update the information.
Thank you in advance!

**Comment by jonahthelion** [comment]
I'm sorry about that - I made the title matching a little more robust and now your paper is included https://github.com/jonahthelion/cvpr_with_code/blob/master/cvpr_2019_github_links.csv#L88

I think I'm still missing a few papers with code though. I'll have to use the authors and/or abstracts to reach 100%.
